// apps/site/src/lib/components/blog/BlogPost.svelte
<script lang="ts">
	import type { BlogPostType } from "../../domain/blogs/types.js";
  import LongFormContent from '../long-form/LongFormContent.svelte';
  import BlogBlurb from './BlogBlurb.svelte';

  export let blog: BlogPostType;
</script>

<BlogBlurb {blog} />
<hr class="my-4" />
<LongFormContent content={blog.body} />
<div class="long-form-content">
  <p class="text-right">&ndash;{blog.author.shortName}</p>
</div>

// reference/ed3dnet-nextjs/components/blog/BlogPost.tsx
import React from "react";

import { type BlogContent } from "../../lib/sanity/queries/blogs/list";
import { LongFormContent } from "../long-form/LongFormContent";

import { BlogBlurb } from "./BlogBlurb";

export type BlogPostProps = {
  blog: BlogContent;
};

export const BlogPost: React.FC<BlogPostProps> = ({ blog }) => {
  return (
    <>
      <BlogBlurb blog={blog} />
      <hr className="my-4" />
      <LongFormContent content={blog.body} />
      <div className="long-form-content">
        <p className="text-right">&ndash;{blog.author.shortName}</p>
      </div>
    </>
  );
};
