// reference/ed3dnet-nextjs/components/blog/BlogCounts.tsx
import clsx from "clsx";
import { sortBy } from "lodash";
import { DateTime } from "luxon";
import Link from "next/link";
import React from "react";

import { type BlogCountsRollup } from "../../lib/sanity/queries/blogs/build-counts";
import { blogCategoryListUrl, blogTagListUrl } from "../../lib/url-builders";

export type BlogIndexProps = {
  rollup: BlogCountsRollup;
  current?: { type: string; value: string };
};

export const BlogCounts: React.FC<BlogIndexProps> = ({ rollup, current }) => {
  return (
    <div>
      <ul className={clsx(["list-none", "margin-none", "text-sm"])}>
        <li
          className={clsx([
            "italic",
            "underline",
            "decoration-dotted",
            "hover:decoration-solid",
            current?.type === "all" && "font-bold",
          ])}
          key="all"
        >
          <Link href="/blog" className="text-base">
            all posts ({rollup.all})
          </Link>
        </li>
        <li key="categories">
          <span className="text-base">categories</span>

          <ul className={clsx(["list-none", "ml-4"])}>
            {sortBy(Object.values(rollup.categories), "slug")
              .filter((category) => category.total > 0)
              .map((category) => (
                <li
                  key={category.slug}
                  title={category.description}
                  className={clsx([
                    "my-0",

                    current?.type === "category" &&
                      current.value === category.slug &&
                      "font-bold",
                  ])}
                >
                  <Link
                    className="italic underline decoration-dotted hover:decoration-solid"
                    href={blogCategoryListUrl(category.slug)}
                  >
                    {category.slug} ({category.total})
                  </Link>
                </li>
              ))}
          </ul>
        </li>
        <li key="tags">
          <span className="text-base">tags</span>

          <div className="ml-4">
            {sortBy(Object.entries(rollup.tags), 1)
              .filter((t) => t[1] > 0)
              .map((t, idx) => (
                <span
                  className={clsx([
                    "inline-block",
                    "italic",

                    idx > 0 && "pl-2",
                  ])}
                  key={t[0]}
                >
                  <Link
                    className="underline decoration-dotted hover:decoration-solid"
                    href={blogTagListUrl(t[0])}
                  >
                    {t[0]} ({t[1]})
                  </Link>
                </span>
              ))}
          </div>
        </li>
        {/* <li key="by-date">
          <span className="text-base">by date</span>

            <ul className={clsx([
              'list-none',
              'ml-4',
            ])}>
              {sortBy(Object.entries(rollup.byMonths), 0).map((t, idx) =>
                <li
                  className={clsx([
                    'my-0',

                    current?.type === 'date' && current.value === t[0] && 'font-bold',
                  ])}
                  key={t[0]}
                >
                  <Link className='underline decoration-dotted hover:decoration-solid' href={`/blog/by-date/${t[0]}`}>
                    {DateTime.fromObject({
                      year: parseInt(t[0].split('-')[0], 10),
                      month: parseInt(t[0].split('-')[1], 10),
                      day: 1,
                    }).toFormat('MMMM yyyy') } ({t[1]})
                  </Link>
                </li>
              )}
            </ul>
          </li> */}
      </ul>
    </div>
  );
};

// apps/site/src/lib/components/blog/BlogCounts.svelte
<script lang="ts">
  import { clsx } from 'clsx';
  import _ from 'lodash';
  import { DateTime } from 'luxon';
  import type { BlogCountsType } from '$lib/domain/blogs/types';
  import { blogCategoryListUrl, blogTagListUrl } from '$lib/url-builders';

  export let rollup: BlogCountsType;
  export let current: { type: string; value: string } | undefined = undefined;
</script>

<div>
  <ul class={clsx(['list-none', 'margin-none', 'text-sm'])}>
    <li
      class={clsx([
        'italic',
        'underline',
        'decoration-dotted',
        'hover:decoration-solid',
        current?.type === 'all' && 'font-bold'
      ])}
    >
      <a href="/blog" class="text-base">
        all posts ({rollup.all})
      </a>
    </li>
    <li>
      <span class="text-base">categories</span>

      <ul class={clsx(['list-none', 'ml-4'])}>
        {#each _.sortBy(Object.values(rollup.categories), 'slug').filter(category => category.total > 0) as category}
          <li
            title={category.description}
            class={clsx([
              'my-0',
              current?.type === 'category' && current.value === category.slug && 'font-bold'
            ])}
          >
            <a
              class="italic underline decoration-dotted hover:decoration-solid"
              href={blogCategoryListUrl(category.slug)}
            >
              {category.slug} ({category.total})
            </a>
          </li>
        {/each}
      </ul>
    </li>
    <li>
      <span class="text-base">tags</span>

      <div class="ml-4">
        {#each _.sortBy(Object.entries(rollup.tags), 1).filter(t => t[1] > 0) as [tag, count], idx}
          <span
            class={clsx([
              'inline-block',
              'italic',
              idx > 0 && 'pl-2'
            ])}
          >
            <a
              class="underline decoration-dotted hover:decoration-solid"
              href={blogTagListUrl(tag)}
            >
              {tag} ({count})
            </a>
          </span>
        {/each}
      </div>
    </li>
    <!-- Commented out in the original React component - keeping commented here too
    <li>
      <span class="text-base">by date</span>

      <ul class={clsx(['list-none', 'ml-4'])}>
        {#each sortBy(Object.entries(rollup.byMonths), 0) as [date, count]}
          <li
            class={clsx([
              'my-0',
              current?.type === 'date' && current.value === date && 'font-bold'
            ])}
          >
            <a
              class="underline decoration-dotted hover:decoration-solid"
              href={`/blog/by-date/${date}`}
            >
              {DateTime.fromObject({
                year: parseInt(date.split('-')[0], 10),
                month: parseInt(date.split('-')[1], 10),
                day: 1
              }).toFormat('MMMM yyyy')} ({count})
            </a>
          </li>
        {/each}
      </ul>
    </li>
    -->
  </ul>
</div>
