// apps/site/src/lib/components/long-form/FigureEpigraph.svelte
<script lang="ts">
  import { QuoteCaption, type QuoteProps } from './_quote-helpers';
  import { PortableText } from '@portabletext/svelte';

  // Using simple props to avoid typing issues
  let { portableText } = $props();

  // Extract values from portableText.value
  let value = $derived(portableText.value);
  let body = $derived(value.body);
  let speaker = $derived(value.speaker);
  let work = $derived(value.work);
  let citeHref = $derived(value.citeHref);

  let caption = $derived(QuoteCaption({ body, speaker, work, citeHref }));
</script>

<figure class="figure-epigraph">
  {#if body}
    <PortableText value={body} />
  {/if}
  {#if caption}
    <figcaption>
      {@html caption.html}
    </figcaption>
  {/if}
</figure>

// reference/ed3dnet-nextjs/components/long-form/FigureEpigraph.tsx
import { PortableText } from "@portabletext/react";
import React from "react";

import { type FigureBlockQuoteProps, makeCitation } from "./_quote-helpers";

export const FigureEpigraph: React.FC<FigureBlockQuoteProps> = (props) => {
  const citation = makeCitation(props);

  return (
    <figure className="figure-epigraph">
      <blockquote cite={props.citeHref}>
        <PortableText value={props.body} />
      </blockquote>
      {citation}
    </figure>
  );
};
