// apps/site/src/lib/components/long-form/LongFormContent.svelte
<script lang="ts">
  import { PortableText } from '@portabletext/svelte';
  import type { PortableTextComponents } from '@portabletext/svelte';
  import type { BlogPostType } from "$lib/domain/blogs/types.js";

  import FigureBlockQuote from './FigureBlockQuote.svelte';
  import FigureEpigraph from './FigureEpigraph.svelte';
  import CenteredBlock from './CenteredBlock.svelte';
  import UnknownBlockStyle from './UnknownBlockStyle.svelte';
  import SidenoteMark from './SidenoteMark.svelte';

  export let content: BlogPostType["body"];

  const components: PortableTextComponents = {
    block: {
      centered: CenteredBlock,
    },
    types: {
      blockQuote: FigureBlockQuote,
      epigraph: FigureEpigraph,
    },
    marks: {
      sidenote: SidenoteMark,
    },
    unknownBlockStyle: UnknownBlockStyle,
  };

  console.log(JSON.stringify(content.filter(block => block._type === 'imageWithAlt'), null, 2));
</script>

<main class="long-form-content">
  <PortableText value={content} {components} />
</main>

// reference/ed3dnet-nextjs/components/long-form/LongFormContent.tsx
import {
  PortableText,
  type PortableTextReactComponents,
} from "@portabletext/react";
import React from "react";

import { FigureBlockQuote } from "./FigureBlockQuote";
import { FigureEpigraph } from "./FigureEpigraph";
import { Sidenote } from "./Sidenote";

const portableTextComponents: Partial<PortableTextReactComponents> = {
  block: {
    centered: ({ children }) => <p className="text-center">{children}</p>,
  },
  types: {
    blockQuote: ({ value }) => (
      <FigureBlockQuote
        speaker={value.speaker}
        work={value.work}
        citeHref={value.citeHref}
        body={value.body}
      />
    ),
    epigraph: ({ value }) => (
      <FigureEpigraph
        speaker={value.speaker}
        work={value.work}
        citeHref={value.citeHref}
        body={value.body}
      />
    ),
  },
  marks: {
    sidenote: ({ value }) => (
      <>
        <span title={JSON.stringify(value)}>{value.text}</span>
        <Sidenote id={value._key} markdown={value.markdown} />
      </>
    ),
  },
  unknownBlockStyle: ({ children }) => <p>UNKNOWN BLOCK STYLE - {children}</p>,
};

export type LongFormContentProps = {
  // TODO: fix this later
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  content: any;
};

export const LongFormContent: React.FC<LongFormContentProps> = (props) => {
  return (
    <main className="long-form-content">
      <PortableText value={props.content} components={portableTextComponents} />
    </main>
  );
};
