// apps/site/src/lib/components/long-form/Sidenote.svelte
<script lang="ts">
  export let id: string;
  export let markdown: string;
</script>

<span class="sidenote-wrapper">
  <label for={id} class="margin-toggle sidenote-number"></label>
  <input type="checkbox" id={id} class="margin-toggle" />
  <span class="sidenote">
    {@html markdown}
  </span>
</span>

// reference/ed3dnet-nextjs/components/long-form/Sidenote.tsx
import { PortableText } from "@portabletext/react";
import { marked } from "marked";
import React from "react";

export type SidenoteProps = {
  id: string;
  markdown: string;
};

export const Sidenote: React.FC<SidenoteProps> = (props) => {
  return (
    <>
      <label
        htmlFor={`sn-${props.id}`}
        className="margin-toggle sidenote-number"
      />
      <input type="checkbox" id={`sn-${props.id}`} className="margin-toggle" />
      <span
        className="sidenote"
        dangerouslySetInnerHTML={{
          __html: "<span>" + marked.parseInline(props.markdown) + "</span>",
        }}
      />
    </>
  );
};
